name: PS Compatibility Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-powershell-5_1:
    name: Test Windows PowerShell 5.1
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        shell: powershell
        run: |
          Write-Host "→ Testing script with Windows PowerShell $($PSVersionTable.PSVersion) (CLR version $($PSVersionTable.CLRVersion)) on $([Environment]::OSVersion.VersionString)"
          .\Recover-GFWLKeys.ps1
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

  test-powershell-core:
    name: Test PowerShell Core ${{ matrix.ps-version }}
    runs-on: windows-latest

    strategy:
      matrix:
        ps-version:
          - 6.0.0
          # - 6.1.0
          # - 6.2.0
          - 7.0.0
          # - 7.1.0
          # - 7.2.0
          # - 7.3.0
          # - 7.4.0
          # - 7.5.0

    steps:
      - uses: actions/checkout@v4

      - name: Install PowerShell Core ${{ matrix.ps-version }}
        uses: PSModule/install-powershell@v1
        with:
          Version: ${{ matrix.ps-version }}

      - name: Run script
        shell: cmd
        env:
          PSVER: ${{ matrix.ps-version }}
        run: |
          echo Testing script with PowerShell Core %PSVER%
          "C:\Program Files\PowerShell\%PSVER%\pwsh.exe" -NoProfile -File .\Recover-GFWLKeys.ps1
          IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%
